version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./configs:/app/configs
      - ./configs/coredns:/etc/coredns:rw
      - ./ssl:/etc/letsencrypt
      - coredns-zones:/etc/coredns/zones
    environment:
      - APP_ENV=development
      - TAILSCALE_API_KEY=${TAILSCALE_API_KEY}
      - TAILSCALE_TAILNET=${TAILSCALE_TAILNET}
    depends_on:
      - coredns
    restart: unless-stopped  # Restart on failure for reliability
    networks:
      - dns-network

  coredns:
    image: coredns/coredns:1.11.1
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "853:853/tcp"
    volumes:
      - ./configs/coredns:/etc/coredns:rw
      - ./configs/coredns/zones:/zones:ro
      - coredns-zones:/etc/coredns/zones
      - ./ssl:/etc/letsencrypt:ro
    command: -conf /etc/coredns/Corefile
    restart: unless-stopped  # Restart on failure, but not if manually stopped
    networks:
      - dns-network

volumes:
  coredns-zones:
    driver: local

networks:
  dns-network:
    driver: bridge
