FROM golang:1.24.3-alpine

RUN apk add --no-cache \
    ca-certificates \
    tzdata \
    netcat-openbsd \
    curl \
    bind-tools \
    git

WORKDIR /app

CMD ["sh", "-c", "cd /app && go test -v ./tests/integration_test.go -tags=integration"]
