app:
  name: dns-manager
  version: 1.0.0
  environment: development

server:
  host: 0.0.0.0
  port: 8080
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s
  tls:
    enabled: false
    port: 8443
    cert_file: /etc/letsencrypt/live/internal.jerkytreats.dev/cert.pem
    key_file: /etc/letsencrypt/live/internal.jerkytreats.dev/privkey.pem
    min_version: "1.2"
    max_version: "1.3"

dns:
  domain: internal.jerkytreats.dev
  coredns:
    config_path: /etc/coredns/Corefile
    zones_path: /etc/coredns/zones
    reload_command: ["kill", "-SIGUSR1", "1"]
    tls:
      enabled: false
      port: 853
      cert_file: /etc/letsencrypt/live/internal.jerkytreats.dev/cert.pem
      key_file: /etc/letsencrypt/live/internal.jerkytreats.dev/privkey.pem

logging:
  level: debug
  format: json
  output: stdout

certificate:
  provider: "lego"
  email: "admin@jerkytreats.dev"
  domain: "internal.jerkytreats.dev"
  ca_dir_url: "https://acme-staging-v02.api.letsencrypt.org/directory"
  renewal:
    enabled: true
    renew_before: "720h" # 30 days
    check_interval: "24h"
  monitoring:
    enabled: true
    alert_threshold: "168h" # 7 days
